name: Build and Deploy API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: cloudm2acr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/api
          push: true
          tags: cloudm2acr.azurecr.io/app-doc-is:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure ACR credentials on App Service
        run: |
          az webapp config container set \
            --name app-doc-is \
            --resource-group doc-dynamic \
            --container-image-name cloudm2acr.azurecr.io/app-doc-is:latest \
            --container-registry-url https://cloudm2acr.azurecr.io \
            --container-registry-user ${{ secrets.ACR_USERNAME }} \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-doc-is'
          images: 'cloudm2acr.azurecr.io/app-doc-is:latest'